---
- include_vars: uf_user_password.yml
- name: Check if Splunk already installed
  stat:
    path: '/opt/splunkforwarder'
  register: splunk_path_present
 
- name: Check if Splunk forwarder package already transferred - 64Bit
  stat:
    path: "{{splunk_working_directory}}{{splunk_uf_file_64bit}}"
  register: splunk_installer_present
  when:
    - ansible_facts['distribution'] == "RedHat"

- name: Check if Splunk forwarder package already transferred - 64Bit
  stat:
    path: "{{splunk_working_directory}}{{splunk_uf_file_64bit}}"
  register: splunk_installer_present
  when:
    - ansible_facts['distribution'] == "Kali"

- name: Check if Splunk forwarder package already transferred - ARM
  stat:
    path: "{{splunk_working_directory}}{{splunk_uf_file_arm}}"
  register: splunk_installer_present
  when:
    - ansible_facts['distribution'] != "RedHat" and ansible_facts['distribution'] != "Kali" 

- name: Copy forwarder over to system - 64Bit
  copy:
    src: /etc/ansible/ansible_playbooks/Splunk_UF_Install/roles/common/files/{{splunk_uf_file_64bit}}
    dest: "{{splunk_working_directory}}"
    owner: splunk
    group: splunk
    mode: 0644
  when:
    - splunk_installer_present.stat.exists == false
    - splunk_path_present.stat.exists == false
    - ansible_facts['distribution'] == "Redhat" or ansible_facts['distribution'] == "Kali"
 
- name: Copy forwarder over to system - Raspberry Pi
  copy:
    src: /etc/ansible/playbooks/Splunk_UF_Install/roles/common/files/{{splunk_uf_file_arm}}
    dest: "{{splunk_working_directory}}"
    owner: splunk
    group: splunk
    mode: 0644
  when:
    - splunk_installer_present.stat.exists == false
    - splunk_path_present.stat.exists == false
    - ansible_facts['distribution'] != "RedHat" and ansible_facts['distribution'] != "Kali" 

- name: Untar Splunk UF Package - 64bit
  command: tar xzf {{splunk_working_directory}}{{splunk_uf_file_64bit}} -C /opt
  args:
    warn: False
  become: yes
  become_method: sudo
  when:
    - splunk_path_present.stat.exists == false
    - ansible_facts['distribution'] == "Redhat" or ansible_facts['distribution'] == "Kali"
 
- name: Untar Splunk UF Package - Raspberry Pi
  command: tar xzf {{splunk_working_directory}}{{splunk_uf_file_arm}} -C /opt
  args:
    warn: False
  become: yes
  become_method: sudo
  when:
    - splunk_path_present.stat.exists == false
    - ansible_facts['distribution'] != "RedHat" and ansible_facts['distribution'] != "Kali" 

- name: Copy user-seed.conf to Forwarder Location
  copy:
    src: /etc/ansible/ansible_playbooks/Splunk_UF_Install/roles/common/files/user-seed.conf
    dest: /opt/splunkforwarder/etc/system/local/
    owner: splunk
    group: splunk
    mode: 0644
  become: yes
  become_method: sudo

- name: Start Splunk Forwarder
  command: /opt/splunkforwarder/bin/splunk start --accept-license
  become: yes
  become_method: sudo

- name: Set Server Name
  command: /opt/splunkforwarder/bin/splunk set servername {{ansible_facts['fqdn']}}
  become: yes
  become_method: sudo

- name: Set Deployment Server
  command: /opt/splunkforwarder/bin/splunk set deploy-poll -auth admin:{{uf_user_password}} https://splunk.unshakeablesalt.net:8089
  become: yes
  become_method: sudo

- name: Set forward-server
  command: /opt/splunkforwarder/bin/splunk add forward-server -auth admin:{{uf_user_password}} splunk.unshakeablesalt.net:9997
  become: yes
  become_method: sudo
 
- name: Enable Boot Start
  command: /opt/splunkforwarder/bin/splunk enable boot-start
  become: yes
  become_method: sudo



 
- name: Restart Splunk forwarder
  command: /opt/splunkforwarder/bin/splunk restart
  become: yes
  become_method: sudo
...